---
title: "Analysis"
author: "Laura Bock Paulsen & Daniel Blumenkranz"
date: "2023-03-27"
output: html_document
---

```{r}
pacman::p_load(tidyverse, ggplot2,sf, rnaturalearth,rnaturalearthdata,RColorBrewer)
```

# Moran's I
The code in this section is made with inspiration from the following tutorial: https://mgimond.github.io/Spatial/spatial-autocorrelation-in-r.html

## Load in needed data
```{r}
cult <- read_csv("data/votes_cultural_similarity.csv", show_col_types = FALSE)
geo <- read_csv("data/votes_geo_nb.csv", show_col_types = FALSE)
votes <- read_csv("data/votes.csv", show_col_types = FALSE)
name_map <- read_csv("data/shortname_mapping.csv", show_col_types = FALSE)
```

## Define functions
```{r}
average_nbh_points <- function(data, points_col) {
  data$avg_nb <- 0
  
  for (i in 1:nrow(data)) {
    neighbours <- data[i,]$countries_similar
    neighbours <- strsplit(neighbours, " ")[[1]]
    
    # the points the country itself got
    points <- data[i,][[points_col]]
    
    # points the neighbours got
    neighbourhood_votes <- data %>% filter(country_sn %in% neighbours)
    
    data[i,]$avg_nb <- mean(c(neighbourhood_votes[[points_col]], points), na.rm = TRUE)
  }
  
  return(data)
}


simulate <- function(data, points_col, n){
  # Create an empty vector
  I.r <- vector(length=n) 
  
  tmp_data <- data
  
  for (i in 1:n){
    # Randomly shuffle income values
    x <- sample(data[[points_col]], replace=FALSE)
    
    tmp_data[[points_col]] <- x
    
    # Compute new set of lagged values
    tmp_data <- average_nbh_points(tmp_data, points_col)
    x.lag <- tmp_data$avg_nb
    
    # Compute the regression slope and store its value
    M.r    <- lm(x.lag ~ x)
    I.r[i] <- coef(M.r)[2]
  }
  
  return(I.r)
}


pseudo_pval <- function(beta, simulated_betas, n){
  N_greater <- sum(beta > simulated_betas)
  p_value <- min(N_greater + 1, n + 1 - N_greater) / (n + 1)
  
  return(p_value)
}


plot_morans_i <- function(data, neibourhood, individual, title){
  ggplot(data, aes(x = individual, y = neibourhood)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "darkblue") + 
  ggtitle(title) +
  theme_light()
}

```

## Calculating Moran's I and pseudo p-value
### Jury - Geographical neighbours

```{r}
point_column <- "points_nb_jury"
average_column <- "jury_avg_nb"
data1 <- geo
n_sim <- 500

M <- lm(data1[[average_column]] ~ data1[[point_column]])
plot_morans_i(data1, data1[[average_column]], data1[[point_column]], "Jury, geographical neighbours")
simulated_correlations <- simulate(data1, points_col = point_column, n = n_sim)

# Plot the histogram of simulated Moran's I values
# then add our observed Moran's I value to the plot
hist(simulated_correlations, main=NULL, xlab="Moran's I", las=1)
abline(v=coef(M)[2], col="red")

p <- pseudo_pval(coef(M)[2], simulated_correlations, n_sim)
paste("Moran's I coef:", coef(M)[2])
paste("psuedo_pval:", p)
```

### Tele - Geographical neighbours
```{r}
point_column <- "points_nb_tele"
average_column <- "tele_avg_nb"
data1 <- geo
n_sim <- 500

M <- lm(data1[[average_column]] ~ data1[[point_column]])
plot_morans_i(data1, data1[[average_column]], data1[[point_column]], "Tele, geographical neighbours")
simulated_correlations <- simulate(data1, points_col = point_column, n = n_sim)

# Plot the histogram of simulated Moran's I values
# then add our observed Moran's I value to the plot
hist(simulated_correlations, main=NULL, xlab="Moran's I", las=1)
abline(v=coef(M)[2], col="red")

p <- pseudo_pval(coef(M)[2], simulated_correlations, n_sim)
paste("Moran's I coef:", coef(M)[2])
paste("psuedo_pval:", p)
```

### Jury - Cultural neighbours
```{r}
point_column <- "points_cult_similar_jury"
average_column <- "jury_avg_nb"
data1 <- cult
n_sim <- 500

M <- lm(data1[[average_column]] ~ data1[[point_column]])
plot_morans_i(data1, data1[[average_column]], data1[[point_column]], "Jury, cultural neighbours")

simulated_correlations <- simulate(data1, points_col = point_column, n = n_sim)

# Plot the histogram of simulated Moran's I values
# then add our observed Moran's I value to the plot
hist(simulated_correlations, main=NULL, xlab="Moran's I", las=1)
abline(v=coef(M)[2], col="red")

p <- pseudo_pval(coef(M)[2], simulated_correlations, n_sim)

paste("Moran's I coef:", coef(M)[2])
paste("psuedo_pval:", p)
```

### Tele - Cultural neighbours
```{r}
point_column <- "points_cult_similar_tele"
average_column <- "tele_avg_nb"
data1 <- cult
n_sim <- 500

M <- lm(data1[[average_column]] ~ data1[[point_column]])
plot_morans_i(data1, data1[[average_column]], data1[[point_column]], "Tele, cultural neighbours")
simulated_correlations <- simulate(data1, points_col = point_column, n = n_sim)

# Plot the histogram of simulated Moran's I values
# then add our observed Moran's I value to the plot
hist(simulated_correlations, main=NULL, xlab="Moran's I", las=1)
abline(v=coef(M)[2], col="red")

p <- pseudo_pval(coef(M)[2], simulated_correlations, n_sim)
paste("Moran's I coef:", coef(M)[2])
paste("psuedo_pval:", p)
```

# PLOTS
## Preparing country polygons

```{r}
cult <- read_csv("data/votes_cultural_similarity.csv", show_col_types = FALSE)
geo <- read_csv("data/votes_geo_nb.csv", show_col_types = FALSE)
votes <- read_csv("data/votes.csv", show_col_types = FALSE)
name_map <- read_csv("data/shortname_mapping.csv", show_col_types = FALSE)
```

```{r}
countries <- ne_countries(scale = "medium", returnclass = "sf")

countries <- st_transform(st_as_sf(countries), crs = 3035)

# rename some countries
countries$sovereignt <- gsub("Macedonia", "North Macedonia", countries$sovereignt)
countries$sovereignt <- gsub("\\band\\b", "&", countries$sovereignt)
countries$sovereignt <- gsub("Republic of Serbia", "Serbia", countries$sovereignt)


# define bbox and use to crop countries
bbox <- st_bbox(c(xmin = 2400000, xmax = 8000000, ymin = 1000000, ymax=6000000), crs = st_crs(3035))

countries_crop <- st_crop(countries, bbox)

# join geo and cult
countries_full <- countries_crop %>% 
                  left_join(geo, by = c("sovereignt"="country")) %>% 
                  left_join(cult, by = c("sovereignt"="country"))



# prepare dataframe for facetting
countries_full_facet <- rbind(countries_full, countries_full, countries_full, countries_full)

# add point type indicator column
countries_full_facet$plot <- c(rep("Cultural neighbours: Jury",74), rep("Cultural neighbours: Televoters",74), rep("Geographic neighbours: Televoters", 74), rep("Geographic neighbours: Jury", 74))

# combine points in same order
countries_full_facet$points <- c(countries_full$points_cult_similar_jury, countries_full$points_cult_similar_tele, countries_full$points_nb_tele, countries_full$points_nb_jury)

```


```{r}
ggplot() +
  geom_sf(data = countries_full_facet, aes(fill=points), color='black', linewidth=0.05) +
  coord_sf(expand = FALSE) +
  facet_wrap(.~plot) +
  scale_fill_gradient2(midpoint=1, low = "darkgreen", high = "darkred", mid = "lightyellow", na.value ='#bdbfbe', name = "Bias score") +
  theme_light() + 
  theme(
    strip.background = element_rect(fill='white', color = "lightgray"),
    panel.background = element_rect(fill = '#daeff7'),
    strip.text = element_text(colour = "black", size = 8),
    #panel.spacing = unit(1, "cm"),
    panel.grid.major = element_line(linewidth = 0.01, color = "white"),
    axis.text.x = element_text(size = 5),
    axis.text.y = element_text(size = 5),
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 8)) 
  

ggsave("figs/plot.jpg")

```

