---
title: "Preprocessing of data"
author: "Laura Bock Paulsen"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, testit)
source("preprocessing_functions.R")
```

# Loading in data

```{r}
votes <- read_csv("data/votes.csv", show_col_types = FALSE)
cultural <- read_csv2("data/cultural_similarity.csv", show_col_types = FALSE)
participants <- read_csv("data/shortname_mapping.csv", show_col_types = FALSE)
```

## Subsetting votes to specific years

```{r}
votes <- votes %>% filter(year >= 2016) %>% filter(round == "final")
```



# Preparing the data frame

```{r}
# looping over all participants
#data <- tibble()

for(i in 1:length(participants$country)){
  country <- participants$country[i]
  country_shortname <- participants$short_name[i]
  
  # looking in both country columns for the given country
  cult1 <- cultural %>% filter(country1 == country)
  cult2 <- cultural %>% filter(country2 == country)
  
  # adding the two data frames together
  cult <- rbind(cult1, cult2)
  
  # sort by index value
  cult <- cult[order(cult$index, decreasing=TRUE),]
  
  # get the 5 most culturally similar countries
  countries <- unique(c(cult$country1[1:5], cult$country2[1:5]))
  
  # remove the country it self
  neighbours <- countries[!countries == country]
  
  # convert neighbours to shortname
  neighbours <- sapply(neighbours, FUN=return_shortname, mapping_data = participants)

  # points from similar countries
  points <- points_from_neighbours(country_shortname, neighbours, votes)

  tmp_data <- tibble(country = country, 
                     country_sn = country_shortname, 
                     countries_similar = paste(neighbours, collapse = ' ', sep = ','),
                     points_cult_similar_jury = points[1],
                     points_cult_similar_tele = points[2]
                     )
  
  # appending the data frame unless i == 1
  if(i==1){
    data <- tmp_data
  }
  else{
    data <- bind_rows(data, tmp_data)
  }
}

# remove rows with NA
data <- data %>% filter(countries_similar != 'NA')
```

```{r}
data$jury_avg_nb <- 0
data$tele_avg_nb <- 0




for(i in 1:nrow(data)){
  neighbours <- data[i,]$countries_similar
  neighbours <- strsplit(neighbours, " ")[[1]]
  
  points_tele <- data[i,]$points_cult_similar_tele
  points_jury <- data[i,]$points_cult_similar_jury
  
  neighbourhood_votes <- data %>% filter(country_sn %in% neighbours)
  
  tele_votes <- mean(c(neighbourhood_votes$points_cult_similar_tele, points_tele), na.rm = T)
  jury_votes <- mean(c(neighbourhood_votes$points_cult_similar_jury, points_jury), na.rm = T)
  data[i,]$jury_avg_nb <- jury_votes
  data[i,]$tele_avg_nb <- tele_votes
  
}
```


```{r}
# save to csv
write.csv(data, "data/votes_cultural_similarity.csv")
```


